package com.elib.entity;

// Generated Nov 14, 2013 2:32:45 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book")
public class Book implements java.io.Serializable {

  private Integer id;
  private String title;
  private String author;
  private String series;
  private String edition;
  private String publisher;
  private Integer year;
  private String language;
  private String identifier;
  private Boolean landscape;
  private Boolean ocr;
  private Boolean kromsated;
  private Boolean color;
  private Boolean bookmarks;
  private Boolean kromsatedByScanmagic;
  private Integer dpi;
  private Integer pages;
  private String extension;
  private String filename;
  private Long filesize;
  private String absolutePath;
  private String downloadUrl;
  private Character md5;
  private Date timeAdded;
  private Date timeLastModified;
  private Set owners = new HashSet(0);
  private Set userlibraries = new HashSet(0);

  public Book() {
  }

  public Book(Date timeAdded) {
    this.timeAdded = timeAdded;
  }

  public Book(String title, String author, String series, String edition, String publisher, Integer year,
          String language, String identifier, Boolean landscape, Boolean ocr, Boolean kromsated, Boolean color,
          Boolean bookmarks, Boolean kromsatedByScanmagic, Integer dpi, Integer pages, String extension,
          String filename, Long filesize, String absolutePath, String downloadUrl, Character md5, Date timeAdded,
          Date timeLastModified, Set owners, Set userlibraries) {
    this.title = title;
    this.author = author;
    this.series = series;
    this.edition = edition;
    this.publisher = publisher;
    this.year = year;
    this.language = language;
    this.identifier = identifier;
    this.landscape = landscape;
    this.ocr = ocr;
    this.kromsated = kromsated;
    this.color = color;
    this.bookmarks = bookmarks;
    this.kromsatedByScanmagic = kromsatedByScanmagic;
    this.dpi = dpi;
    this.pages = pages;
    this.extension = extension;
    this.filename = filename;
    this.filesize = filesize;
    this.absolutePath = absolutePath;
    this.downloadUrl = downloadUrl;
    this.md5 = md5;
    this.timeAdded = timeAdded;
    this.timeLastModified = timeLastModified;
    this.owners = owners;
    this.userlibraries = userlibraries;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "ID", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @Column(name = "Title", length = 500)
  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Column(name = "Author", length = 300)
  public String getAuthor() {
    return this.author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  @Column(name = "Series", length = 200)
  public String getSeries() {
    return this.series;
  }

  public void setSeries(String series) {
    this.series = series;
  }

  @Column(name = "Edition", length = 50)
  public String getEdition() {
    return this.edition;
  }

  public void setEdition(String edition) {
    this.edition = edition;
  }

  @Column(name = "Publisher", length = 100)
  public String getPublisher() {
    return this.publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  @Column(name = "Year")
  public Integer getYear() {
    return this.year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  @Column(name = "Language", length = 20)
  public String getLanguage() {
    return this.language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  @Column(name = "Identifier", length = 100)
  public String getIdentifier() {
    return this.identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  @Column(name = "Landscape")
  public Boolean getLandscape() {
    return this.landscape;
  }

  public void setLandscape(Boolean landscape) {
    this.landscape = landscape;
  }

  @Column(name = "Ocr")
  public Boolean getOcr() {
    return this.ocr;
  }

  public void setOcr(Boolean ocr) {
    this.ocr = ocr;
  }

  @Column(name = "Kromsated")
  public Boolean getKromsated() {
    return this.kromsated;
  }

  public void setKromsated(Boolean kromsated) {
    this.kromsated = kromsated;
  }

  @Column(name = "Color")
  public Boolean getColor() {
    return this.color;
  }

  public void setColor(Boolean color) {
    this.color = color;
  }

  @Column(name = "Bookmarks")
  public Boolean getBookmarks() {
    return this.bookmarks;
  }

  public void setBookmarks(Boolean bookmarks) {
    this.bookmarks = bookmarks;
  }

  @Column(name = "KromsatedByScanmagic")
  public Boolean getKromsatedByScanmagic() {
    return this.kromsatedByScanmagic;
  }

  public void setKromsatedByScanmagic(Boolean kromsatedByScanmagic) {
    this.kromsatedByScanmagic = kromsatedByScanmagic;
  }

  @Column(name = "Dpi")
  public Integer getDpi() {
    return this.dpi;
  }

  public void setDpi(Integer dpi) {
    this.dpi = dpi;
  }

  @Column(name = "Pages")
  public Integer getPages() {
    return this.pages;
  }

  public void setPages(Integer pages) {
    this.pages = pages;
  }

  @Column(name = "Extension", length = 5)
  public String getExtension() {
    return this.extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  @Column(name = "Filename", length = 1000)
  public String getFilename() {
    return this.filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  @Column(name = "Filesize")
  public Long getFilesize() {
    return this.filesize;
  }

  public void setFilesize(Long filesize) {
    this.filesize = filesize;
  }

  @Column(name = "AbsolutePath", length = 300)
  public String getAbsolutePath() {
    return this.absolutePath;
  }

  public void setAbsolutePath(String absolutePath) {
    this.absolutePath = absolutePath;
  }

  @Column(name = "DownloadUrl", length = 300)
  public String getDownloadUrl() {
    return this.downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  @Column(name = "MD5", length = 1)
  public Character getMd5() {
    return this.md5;
  }

  public void setMd5(Character md5) {
    this.md5 = md5;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "TimeAdded", nullable = false, length = 19)
  public Date getTimeAdded() {
    return this.timeAdded;
  }

  public void setTimeAdded(Date timeAdded) {
    this.timeAdded = timeAdded;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "TimeLastModified", length = 19)
  public Date getTimeLastModified() {
    return this.timeLastModified;
  }

  public void setTimeLastModified(Date timeLastModified) {
    this.timeLastModified = timeLastModified;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
  public Set getOwners() {
    return this.owners;
  }

  public void setOwners(Set owners) {
    this.owners = owners;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
  public Set getUserlibraries() {
    return this.userlibraries;
  }

  public void setUserlibraries(Set userlibraries) {
    this.userlibraries = userlibraries;
  }

}
