package com.elib.entity;

// Generated Nov 16, 2013 10:36:05 PM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Owner generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "owner")
public class Owner implements java.io.Serializable, IEntity<Integer> {

  private Integer id;
  private Book book;
  private User user;

  public Owner() {
  }

  public Owner(Book book, User user) {
    this.book = book;
    this.user = user;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "ID", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.REFRESH})
  @JoinColumn(name = "BookID")
  public Book getBook() {
    return this.book;
  }

  public void setBook(Book book) {
    this.book = book;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "UserID")
  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

}
