package com.elib.entity;

// Generated Nov 16, 2013 10:36:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user")
public class User implements java.io.Serializable, IEntity<Integer> {

  private Integer id;
  private String firstName;
  private String lastName;
  private String email;
  private String password;
  private Date dateOfBirth;
  private String avatar;
  private int roleId;
  private Set<Userlibrary> userlibraries = new HashSet<Userlibrary>(0);
  private Set<Owner> owners = new HashSet<Owner>(0);

  public User() {
  }

  public User(String firstName, String lastName, String email, String password, Date dateOfBirth, int roleId) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.password = password;
    this.dateOfBirth = dateOfBirth;
    this.roleId = roleId;
  }

  public User(String firstName, String lastName, String email, String password, Date dateOfBirth, String avatar,
          int roleId, Set<Userlibrary> userlibraries, Set<Owner> owners) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.password = password;
    this.dateOfBirth = dateOfBirth;
    this.avatar = avatar;
    this.roleId = roleId;
    this.userlibraries = userlibraries;
    this.owners = owners;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "ID", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @Column(name = "FirstName", nullable = false, length = 40)
  public String getFirstName() {
    return this.firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  @Column(name = "LastName", nullable = false, length = 40)
  public String getLastName() {
    return this.lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  @Column(name = "Email", nullable = false, length = 30)
  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  @Column(name = "Password", nullable = false, length = 40)
  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "DateOfBirth", nullable = false, length = 19)
  public Date getDateOfBirth() {
    return this.dateOfBirth;
  }

  public void setDateOfBirth(Date dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  @Column(name = "Avatar", length = 60)
  public String getAvatar() {
    return this.avatar;
  }

  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  @Column(name = "RoleID", nullable = false)
  public int getRoleId() {
    return this.roleId;
  }

  public void setRoleId(int roleId) {
    this.roleId = roleId;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
  public Set<Userlibrary> getUserlibraries() {
    return this.userlibraries;
  }

  public void setUserlibraries(Set<Userlibrary> userlibraries) {
    this.userlibraries = userlibraries;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
  public Set<Owner> getOwners() {
    return this.owners;
  }

  public void setOwners(Set<Owner> owners) {
    this.owners = owners;
  }

}
